version: 1.0
app:
  instances:
    min: 1
    max: 1
  #version: ""
   version: "ecba95b7-a3ce-41b6-9468-9a68f94c4d70"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=prod"
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
