version: 1.0
app:
  instances:
    min: 1
    max: 1
  #version: ""
   version: "8ebe3f42-61dd-486c-beda-560751e1de3e"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=prod"
    - name: test_Value
      value: "testData"
    - name: MAX
      value: "5"
